CREATE TABLE book (
  id SERIAL PRIMARY KEY NOT NULL,
  isbn BIGINT NOT NULL,
  bname CHARACTER VARYING(100) NOT NULL,
  price REAL NOT NULL,
  quantity INTEGER NOT NULL,
  status CHARACTER VARYING(100)
);
CREATE UNIQUE INDEX book_isbn_uindex ON book USING BTREE (isbn);